### ISSUE TITLE
Add a dynamic dropdown list in form.html

### ISSUE THREAD

**Issue by abhishek-bodapati** [abhishek-bodapati/COVID_E-Pass_India#1]
- Add a dynamic drop-down list in `templates/form.html`
- The drop-down list should consist source and destination states and districts from [here](https://api.covid19india.org/v5/data.json)
- If a source district is selected make sure it doesn't appear in the destination district dropdown list

**Comment by nik-hz** [comment]
hello I am a first timer, can you assign this to me pls

**Comment by heidage** [comment]
May i know..are u using python to make ur website? In ur drop-down list do u want the source, destination states and districts all in different tabs?

**Comment by abhishek-bodapati** [comment]
> May i know..are u using python to make ur website? In ur drop-down list do u want the source, destination states and districts all in different tabs?

- I have used python flask for routing and making the static pages dynamic. 
- The file which you need to change is `templates/form.html`.
- All the 4 drop-down lists must be in the same tab. It should look something this.
![Screenshot 2021-05-30 at 11 09 45 AM](https://user-images.githubusercontent.com/47183749/120093444-f4d69e00-c137-11eb-8624-484148650e2e.png)
- You can either use Python Flask or a Javascript code snippet for this.
-  Please let me know if you're interested to contribute so that I can assign this issue to you.

**Comment by heidage** [comment]
I am able to use python flask but i will require some time. I am interested to contribute

**Comment by heidage** [comment]
I am done with the form.html, i was able to add the dropdown list for the Source states ,source districts, destination states and destination districts. I have also added the function where by the destination district does not contain the selected source district

**Comment by heidage** [comment]
How should i pass u the edited code? sorry im new to this

**Comment by abhishek-bodapati** [comment]
Did you fork this project?
If not fork it, push your changes to your forked repo. Create a PR!

**Comment by heidage** [comment]
Hi i did a pull request. Please check. if anything went wrong im sorry
