### ISSUE TITLE
Disable previous date in `form.html`

### ISSUE THREAD

**Issue by abhishek-bodapati** [abhishek-bodapati/COVID_E-Pass_India#3]
- Disable the option to select the previous date in `templates/form.html`
- The user should be able to select only the current date and the future dates.

**Comment by heidage** [comment]
Hello again, i can help you out with this HAHAHAH

**Comment by abhishek-bodapati** [comment]
> Hello again, i can help you out with this HAHAHAH

Sure, go ahead!

**Comment by heidage** [comment]
Hi i have done a PR. Please check if it is okay:)
